---
title: "Essentials of Data Analytics"
author: "19BCE1395-Trishit Chakraborty"
date: "13/4/2022"
output:
  word_document: default
  html_document: default
subtitle: Ex-6
---

#####  Loading the packages

```{r, echo=TRUE}
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
```


#####  Reading the dataset

```{r, echo=TRUE}
dt<-read.csv('dataset.csv')
str(dt)
dt$admit<-as.factor(dt$admit)
dt$rank<-as.factor(dt$rank)
```


#####  To check the independence of attributes among them

```{r, echo=TRUE}
pairs.panels(dt)
```


#####  Plotting box plot and density plot

```{r, echo=TRUE}
dt %>% # to have initial look up of 
  ggplot(aes(x=admit,y=gre,fill=admit))+
  geom_boxplot()+
  ggtitle('Admit Box Plot based on GRE Score')
dt %>%
  ggplot(aes(x=gre,fill=admit))+
  geom_density(alpha=0.75,color='black')+
  ggtitle('Density Plot based on GRE Score')
```


#####  Splitting the dataset into train and test set

```{r, echo=TRUE}
set.seed(234)
smpl<-sample(2,nrow(dt),replace=T,prob=c(0.8,0.2))
train<-dt[smpl==1,]
test<-dt[smpl==2, ]
```


#####  Building the Naive bayes model

```{r, echo=TRUE}
mdl<-naive_bayes(admit~ .,data=train)
mdl
plot(mdl)

p<-predict(mdl,train,type='prob')
head(cbind(p,train))
```


#####  To find the accuracy of prediction

```{r, echo=TRUE}
p1<-predict(mdl,train)
(tab1<-table(p1,train$admit))
1-sum(diag(tab1))/sum(tab1)
```